### ISSUE TITLE
写真

### ISSUE THREAD

**Issue by miya0001** [wakayama-hacker/wmap#24]
ギャラリー的な何かを表示できるタグ

**Comment by kamataryo** [comment]
![wmap-gallery](https://cloud.githubusercontent.com/assets/6292312/23831142/32a545a8-075e-11e7-8c3f-7b7634d7886e.gif)

**Comment by kamataryo** [comment]
画像表示タグを追加してみました。https://github.com/wakayama-hacker/wmap/commit/c557614a612ef9d9cd836730eebb73bf4dcfeb41

imageフィールドで `./images`に入れた画像のファイル名を指定するようにしています。
`npm run build`の際にサムネイル用の画像を生成するようにしようと思います。
