### ISSUE TITLE
エンドポイントURLを指定してCSVファイルやエクセルファイルを取り込む

### ISSUE THREAD

**Issue by kamataryo** [wakayama-hacker/wmap#31]
データのビルドでこういうこともできると、オープンデータ利用の観点からいいかもです。
エンドポイントURLを指定して、データを収穫します。

#### data/endpoints

```
http://example.com/example.csv
http://example.com/foo/bar.xlsx
```

#### gulpfile.js

```
const gulp    = require( 'gulp' )
const harvest = require( './lib/harvest' )

gulp.task( 'harvest' () => {
    harvest( './data/endpoints' )
    .pipe( csv2json() )
    .pipe( gulp.dest( './json' ) )
} )
```

**Comment by miya0001** [comment]
別のプロジェクトとしてやりましょう。リモートのデータのフォーマットを合わせる何かが必要なので汎用的にやろうと思うと複雑になるわりに意外と便利じゃない気がします。

**Comment by miya0001** [comment]
CSVは `data` ディレクトリに入れないで、`npm run build` で持ってくるように修正。
実際に作ってみたらローカルのCSVは無視でいいと思った。

以下のIssueとセットで対処する
https://github.com/wakayama-hacker/wmap/issues/63

**Comment by miya0001** [comment]
やてみたら便利じゃなかったのといろいろ無理があった。
