### ISSUE TITLE
wnewの名前の変更

### ISSUE THREAD

**Issue by amuy841** [wakayama-hacker/wmap#36]
wnewの中身がわからないため

**Comment by miya0001** [comment]
wakayama + map + app
で wmapp ってどうですかね？

**Comment by kamataryo** [comment]
+1

**Comment by kamataryo** [comment]
同じ名前だとこのようなものがありましたが、内容では重複しなさそうです。
https://ja.osdn.net/projects/freshmeat_wmapp/
