### ISSUE TITLE
iPhoneでメニューの操作性が悪い

### ISSUE THREAD

**Issue by kamataryo** [wakayama-hacker/wmap#38]
```
Home  >
串本    >
...
```
をタップした時に、個別のページへの遷移に違和感がある。

**Comment by miya0001** [comment]
* [Ajax リクエストの前に閉じる処理を行うようにした。](https://github.com/wakayama-hacker/wnew/blob/master/tags/menu-item.tag#L16-L17)
* [`menu.json` のリクエスト時にクエリーを追加するなどのキャッシュコントロールの改善](https://github.com/wakayama-hacker/wnew/blob/master/src/app.js#L45)

などによりとりあえず改善したと思います。
