### ISSUE TITLE
クライアントサイドルーターの導入

### ISSUE THREAD

**Issue by kamataryo** [wakayama-hacker/wmap#40]
個別のページにURLを発行する。

**Comment by miya0001** [comment]
これは後から実装するものではないので一旦閉じます。
必要性が出て来たら、個別の機能ごとに実装する感じで。

**Comment by miya0001** [comment]
やっぱりこれやります。僕やります。

**Comment by miya0001** [comment]
http://example.com/#hello/12345

```
router( 'hello', function( div, id ) {
  // div.innerHTML = id
  // riot.mount( div, 'hello', { id: id } )
} )
```

みたいな感じ

**Comment by miya0001** [comment]
https://github.com/wakayama-hacker/wnew/blob/master/src/app.js#L110-L133
