### ISSUE TITLE
JSONのキャッシュ対策

### ISSUE THREAD

**Issue by miya0001** [wakayama-hacker/wmap#51]
CSVからJSONに変換する際に生成されるIDを連番ではなくランダムな固定長の文字列、たとえばmd5などに変更する。
この文字列はgulpを実行するたびに毎回ランダムな値になったほうがいいかも。

**Comment by kamataryo** [comment]
ビルド後のJavaScriptとCSSも bundle-{hash}.min.js のようにハッシュを付けたいです。

**Comment by miya0001** [comment]
JSとかCSSは、めんどくさそうなので保留にしましょう。笑
