### ISSUE TITLE
APIとアプリケーションの分離

### ISSUE THREAD

**Issue by miya0001** [wakayama-hacker/wmap#56]
CSVやExcelからAPIを生成してgh-pagesを提供する部分を、別のリポジトリにわけたほうがいいかも。

メリット

* アプリケーションのリポジトリがシンプルになる。
* いろんなデータでのデモがやりやすい
* いろんなユースケースを想定しやすくなるかも

デメリット

* ドキュメントの導線がわかりにくくなるかも
* 説明がめんどくさくなるかも

**Comment by miya0001** [comment]
@KamataRyo どう思います？

**Comment by kamataryo** [comment]
悩ましいですが、使ってもらう上でオールインワンのシンプルさは捨て難いように思えます。
`endpoint`パラメータが指定された時にだけ外を向く設定でいいのではないでしょうか。

あと、ささやかではありますが、`./lib`以下のGulpプラグインは、別リポジトリに分離してnpmで公開すれば、wnewのリポジトリを少しだけシンプルにできそうです。

**Comment by kamataryo** [comment]
その他の案として、リポジトリを分離した上で、`git submodule`するのはいかがでしょうか。wnewをシンプルに保つことにはあまり寄与しないかもしれないですが..

**Comment by miya0001** [comment]
git submoduleはいやです。笑

**Comment by miya0001** [comment]
https://github.com/wakayama-hacker/wmap/issues/31
