### ISSUE TITLE
CSVからJSONに変換するGulpプラグインをつくる

### ISSUE THREAD

**Issue by miya0001** [wakayama-hacker/wmap#9]
CSVのフォーマットは以下のとおり

```csv
menu,title,lat.lng,content,...
串本,橋杭岩,12.345,123.45,これは橋杭岩です,...
```

これを以下のようなフォーマットのJSONに変換する

```
{
  "串本": [
    {
      "title": "橋杭岩"
      "lat": "12.345",
      "lng": "123.45",
      "content": "これは橋杭岩です"
    },
    {
      ...
    },
    ...
  ]
}
```

**Comment by kamataryo** [comment]
誰か着手されてますか？
いなければやります！

**Comment by miya0001** [comment]
お願いします！

**Comment by miya0001** [comment]
あっ、これじゃだめだ。

`menu.json` と `串本.json` にわけて出力されるといいかも。

`menu.json` は、`menu` っていう列の単純な配列。
`串本.json` は、`menu` に`串本`と記述された行の配列。

```串本.json
[
    {
      "title": "橋杭岩",
      "lat": "12.345",
      "lng": "123.45",
      "content": "これは橋杭岩です"
    },
    {
      ...
    },
    ...
]
```

最終的には、メニューで `串本` を選択したら `串本.json` がロードされるイメージ。
日本語のファイルをgh-page上でAjaxでリクエストできるかから試していただけると。

こういう構造ならデータのメンテが非エンジニアでもできるようになるので。

**Comment by miya0001** [comment]
あと、複数のCSVを扱えるようにするといいかも。たとえばデータが多いときに `串本.csv` と `すさみ.csv` みたいに分けてデータを作れるといいですね。

CSV から json に変換する gulp のプラグインのサンプルは以下にあります。
https://github.com/madefor/postal-code-api/tree/master/lib

**Comment by miya0001** [comment]
あと、menuの項目は自治体とは限らないです。たとえば`公衆トイレ`とかになるかも。

**Comment by kamataryo** [comment]
日本語ファイル名でもOKみたいです。
https://kamataryo.github.io/test-ajax-with-gh-pages/
今からプラグインを作ります。

**Comment by kamataryo** [comment]
done at #12
